language: java
cache:
  directories:
  - "~/.m2/repository"
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn package -B
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: wt5HS9YhQ8hXzE124Wue8XrC0hTcdGoV6wYr2A+uIpkA9oSlsZFU7VKj5qxPf3WjvTp06Qf9Ymj1boohXWeAbERTpXFcII65k5of62J2rFPJQJa8l3caYMiP5POgx3gEuEvJFBAXBmUoHPUj3mMg/Tkg4r1fmFdaPpR0tMIR3VAhQT44yaGMFRaqyVcRLKT396h8e7KPkkdVTmXRyhrSOZ26goqtPu5J270Mn/0QMiSlR3mbGpYLRtkuudCakykpVaBZ72NbNmk1vwLf3HN8Ept1qifWZvBDv6fYQVBs5KNUniiBgH8KqxXjkt02kUHulCpm44VORMRx239ubQOADQ5chZGVz+GYlWEAooeb+p1v5xmQp0onsGerMUvgva/eEwlNZgENZ6h1QvChy8c3ZgSF/a0VUVtUbM653Ic2aLfTZNdkT7HmQParZ/4sb0+MsL541dPN7pxaSUmwBXdvmeWTm87r0PYSBcQEc1gXrRFdf4A5lVpFRxDdOpQluX32fzLu4+aAZ2j1kdEyNNMh+sRI1O43rGn/aGOz8Zt4T7NclAVdlMs5TudKL4EKUVCKmijrNrh1hmhEqTeRUm7bCgn7DTKlq26nN9YmacC2/gE+6OzRLpJlDVwY8Rpa2WTWfGBGa5bhh4As91rqKIWrgtOdpuo9nFRINFD/S2rHKP0=
  file: target/base-*.jar
  file_glob: true
  on:
    repo: dm-drogeriemarkt/mail2blog-base
    branch: master
    tags: true
- provider: script
  skip_cleanup: true
  script: cd/deploy.sh
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST == 'false'"
    tags: true
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - OSSRH_JIRA_USERNAME=mail2blog
  - GPG_KEY_NAME=mail2blog.dmDeutschland@dm.de
  - secure: QmflSE8jsIqmQyo3YpGGx+ebx3y51lV6jwzDZtWeVzu6Y3hFVvfuM+hH9bQsQhIxWYasByBkAAcw+IESOg7igYUermUDs9l/Jc2R2VENY8Tlw3gYtOg0dFpMs6f40i/Elz2qTUWr7VY9UAdwE7+TnSEa+PWUDx5D2+XYSmNaB6cHELpJngCWRXNuzEGuTbOEZNZ+ha9Iu9d437NVOWDZOfOHUPbd5M7aKitXFbDIG3XsOSebCkMj4fUfUEi+k0fJ7dvfNba8ACQRwwWSZ8r/Ah1a2rK8vUezV9iw4VVNP3WAK81oSnL4jwhHKqp5YGranZEA2Ku2WlfWOeXIDbWgx/6GLXYbkzUkXdGZAJWga0gYg+do4weaSXkF4/7Ly9zd6yKfsjJ7cqCsyID9ZsRXQHSDMxCMGZ6d1prmw8SH+VDqWuKKtQmdsBwR3nXqp3MCtx6yaChd6ulbe4+eyjX3R16FDio/uQYouAyHOytbPJEC/1mFDdZ4hBHiu/D98Edqq/rFUZcLjmb/TtKS5epTEAi9Tfld/xv4SyrdW2PN0Hs6SfN8KXQMivGjKsxgv/Y0bRS0TnWvvaMH/RQgsxWxbV4LYgvbijoB6Q+xwEB9jXfj24oJDcEpCekW1XRB56FAiDBtsYb5wZjQ6207orjiqd++eHmPjbhf6axahFe8KlQ=
