language: java
cache:
  directories:
  - "~/.m2/repository"
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn package -B
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: VqEwCzfMWLkWCozidJWvGMbE6ue49trH53+PgwpXZQNJjeG1j1vV+MWPkmIcO399Fca1kjKHLOjG8IpyHgwWzsEHtQ5US21DQ3tIWHsKjedtEOpj82GxaYyp7lGccFGe+3tfdyS2et3s/a8qf0DNNvWM3xBcpE6+IQ6FzhFt18M6ctnJzkMYrFk/DyNacRdqPbKNFCMzeKrQ5EO/hZ5x/o2jmsresaB1Iliq+oz6/3jnuBDsU5O/+jQses6WNMmjtq6ucXXwHbjNEoYByxVir6NAKz5y5p8WkkaFZ9kXd/lvMuVOiz5QzU3AJAKuqTK2exXqPMngQtKt3/wwtQpEgmw8unnhwgyd2iYXazR5AgJXyH59srFFHiJ4DSGxIImPr+bFtr4mGgpfUUE3es//Z+4QDkMyBYPDQz+fRFUjjk2Rz7JV2sTd2nVQfk4nU/LXz4LZCsuVvgvJnguUHxqCDU88iOCCmNLBgu98+P03LfVOmPjvypYPPHXCxwSBSEYboIAemM2lVPcgJGuTrYfcWru8ZACNzk8aq7/SUKfJILAGuYCHVEeB8IJeHlHqWlBb2j3xbAF4GaWRoipAXQB0B0/yzMM3hQBteuQmfHRy/UqSsj2fKIFQ9xNpnf6jvZW75ut1cZxN4xuzL3RmEh/spe/YZL+S8ZpemRAq7JHcQjU=
  file: target/base-*.jar
  file_glob: true
  on:
    repo: dm-drogeriemarkt/mail2blog-base
    branch: master
    tags: true
- provider: script
  skip_cleanup: true
  script: cd/deploy.sh
  on:
    branch: master
    condition: "$TRAVIS_PULL_REQUEST == 'false'"
    tags: true
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - OSSRH_JIRA_USERNAME=mail2blog
  - GPG_KEY_NAME=mail2blog.dmDeutschland@dm.de
  - secure: Ap/rByhC967Pq6lbmDweOijYlQ0nQ5J1ECSOfr64gEYG7pGoTd50RyjnipKFegJD++GeYTouIKWodxJOXSPILoY/rwV8fh5Lb+kJVsD2xFRlLWbuJa6c2NyRoczZlAnVEkL+Mg7bDFOferlqLI4ciEAvb6r4tEqDPX6/EUBZcjel/MTJTNIPgVXHCMNYEm3rIkOmzVUZ25ZlKEIKPUSJnpb6Nb7l4Ax8/U1sAUQDpLEtJGUlay2j1Vw5ijnN5bK79BqgkvQlKKbWY+AJnyyNhCL5VTFM2AwXO3Mzy1BXk29CDAorSD0MzpqDIS3SnhM0HmMtPAc8X9u9PI+rwVMnbB3mp/caDdfhzov0SKgc4yWEwEU6yeHWbLYG1hW4NeEP1FFahZSaWwY4KUxGZ+JIBgvxmyxmuAX1o+nQUvGjFpcJQI/iG3FzjM/FluF59cIzdnH2/Ju/b/QCxuFDpIrdt7w9N4ZjDnz+IUHj6VTTM0AL722dIEIoFg4XIY2frJp3Q/g5gaoQMiZlLqHhevMlPVCMeG+9FMYttdRY/innHtylvaKOwHVz7OG9ZSt4tYIQtmo0UOG0Cu7daTMSpfiy8HIaRmOPh4PUCECink6o9t1gMgNSE+/NhT5eBVTZ9FrcwDcxsCuP4Nt5gGYLnDCHjgwjEw42G80Qu4crhTB97Wo=
